apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-escolar
  namespace: gestao-escolar
  labels:
    app: api-escolar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-escolar
  template:
    metadata:
      labels:
        app: api-escolar
    spec:
      restartPolicy: Always
      containers:
      - name: api-escolar
        image: us-central1-docker.pkg.dev/quantum-backup-467623-t3/api-escolar-repo/api-escolar:main-d69779e
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: api-escolar-config
              key: DATABASE_URL
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: api-escolar-config
              key: LOG_LEVEL
        - name: API_TITLE
          valueFrom:
            configMapKeyRef:
              name: api-escolar-config
              key: API_TITLE
        - name: API_VERSION
          valueFrom:
            configMapKeyRef:
              name: api-escolar-config
              key: API_VERSION
        volumeMounts:
        - name: database-storage
          mountPath: /app/db
          subPath: escola.db
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
      volumes:
      - name: database-storage
        persistentVolumeClaim:
          claimName: api-escolar-pvc
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000 